---
name: "Collection Tags"
guid: "190D5E0E-FA7A-430A-B739-4E9D1D2363D7"
version: "0.1.0.1"
targetAbi: "10.10.0.0"
framework: "net8.0"
overview: "Erstellt Tags basierend auf Collections z.B. um Inhalte sperren für User zu erstellen."
description: >
  Mit Collection Tags werden automatisch Tags erzeugt, die den Namen der Jellyfin Collections  entsprechen. Da Collections in Jellyfin im Grunde Ordner für Serien und Filme sind, können diese  automatisch erzeugten Tags dazu genutzt werden, Inhalte für bestimmte Benutzergruppen zu  sperren oder freizugeben. Dies ermöglicht eine flexiblere und fein abgestimmte Verwaltung der  Medieninhalte.

category: "General"
owner: "Minegamer06"
artifacts:
  - "Jellyfin.Plugin.CollectionTags.dll"
changelog: >-
  ["Update manifest.json","Update release.yml","Update build.yaml and manifest.json for release version 0.1.0.1","Update manifest.json","Update release.yml","Update manifest.json","Update build.yaml and manifest.json for release version 0.1.0.1","Update PluginConfiguration.cs","Update release.yml","Update Jellyfin.Plugin.CollectionTags.csproj","Bedinug korrigiert","Erster Build Test","Now the Plugin should work","Config Erweitert","Nichtbenötigt dinge aus Template entfernt, Template in CollectionTags umbennatn PluginConfiguration.cs angepasst","Initial commit"]
