---
name: "Collection Tags"
guid: "190D5E0E-FA7A-430A-B739-4E9D1D2363D7"
version: "0.2.0.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Erstellt Tags basierend auf Collections z.B. um Inhalte sperren für User zu erstellen."
description: >
  Mit Collection Tags werden automatisch Tags erzeugt, die den Namen der Jellyfin Collections  entsprechen. Da Collections in Jellyfin im Grunde Ordner für Serien und Filme sind, können diese  automatisch erzeugten Tags dazu genutzt werden, Inhalte für bestimmte Benutzergruppen zu  sperren oder freizugeben. Dies ermöglicht eine flexiblere und fein abgestimmte Verwaltung der  Medieninhalte.

category: "General"
owner: "Minegamer06"
artifacts:
  - "Jellyfin.Plugin.CollectionTags.dll"
changelog: >-
  ["Update release workflow for .NET and target ABI","Bump version from 0.1.0.1 to 0.2.0.0","Update build.yaml and Directory.Build.props for version 0.2.0.0 and target framework net9.0","Update target framework to net9.0 and package references to version 10.11.0","Update README.md"]
